### ISSUE TITLE
Teleporting Workers

### ISSUE THREAD

**Issue by Ezaco** [ostinelli/SCAR_UCM#16] opened 2017-11-03 18:01 UTC
Played with it for about an hour with another player, and found out what they meant by AI 'randomly dying'.
 
When I have ten workers in the area (which, tbh, is a little much, but you know, testing) sometimes some of the AI will get teleported out to the edge of the map. On one occasion it was only one, on another it was 6 different AI.
 
As requested, here is a screenshot of our settings:
 
https://imgur.com/a/kw2Cj
 
For additional reference, here is a screenshot of the construction they're building. It's intended to be a checkpoint.
 
https://imgur.com/a/FdWEM

Steps to reproduce:

1) Create mission with 10 maximum workers.
2) Start mission. Transport materials and workers to construction site.
3) When workers begin to work, visually identify if all are still at the site. If so, simply wait until the next piece, or any piece at which point you see less than the 10 workers.
4) Enter Zeus and check map. AI will be in the ocean.

**Comment by ostinelli** [comment] 2017-11-06 09:37
Does where they get teleported correspond to coordinates `[0, 0, 0]`?

**Comment by Ezaco** [comment] 2017-11-06 12:52
No. They kind of get sprayed out in a circle.

**Comment by ostinelli** [comment] 2017-11-06 16:48
Can you confirm that you are using the latest from Steam (not armaholic, which at a given point reported v0.13.0 when in fact it wasn't)?

**Comment by Ezaco** [comment] 2017-11-06 20:54
I am using Steam, yes.

**Comment by ostinelli** [comment] 2017-12-05 15:08
I am sorry but can't reproduce still. Can you please provide a mission that I can try out?

**Comment by ostinelli** [comment] 2017-12-12 18:10
e9764f427f16eab26ada63c64f854de2d4a36265 should fix it. I will provide a build tonight, let me know if this solves it for you.

**Comment by ostinelli** [comment] 2017-12-18 19:34
No follow up, closing. Reopen if you encounter the same error, thanks.

**Closed as completed by ostinelli** 2017-12-18 19:34 UTC
